language: c
compiler:
  - gcc
#  - clang # Travis clang is too old for now
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yq linux-headers-generic --fix-missing
  - sudo apt-get install -yq sparse --fix-missing
script: cd src && make kernel_version=\* C=2 COMPILATION_CHECKS=y CC=${CC}
install: true
