#
# Variables needed to build the kernel module
#
name      = secure_log
src_files = log.c
 
obj-m += $(name).o
$(name)-y := $(src_files:.c=.o)
ccflags-y  += -D'MODULE_NAME="$(name)"' -I"$(src)/../lib"
