name      = netlog
src_files = retro-compat.c probes.c whitelist.c proc_config.c netlog_module.c 
 
obj-m += $(name).o
$(name)-y := $(src_files:.c=.o)
ccflags-y  += -D'MODULE_NAME="$(name)"' -I$(src)/../secure_logs
