name      = netlog
src_files = probes.c whitelist.c netlog_module.c ../lib/probes_helper.c
 
obj-m += $(name).o
$(name)-y := $(src_files:.c=.o)
ccflags-y  += -D'MODULE_NAME="$(name)"' -I"$(src)/../secure_log" -I"$(src)/../lib"
